### PR TITLE
First draft for student readme

### PR DESCRIPTION
**Pull request by hcastilho**

### CODE REVIEW

**Comment by rjna** [comment]
Suggestions:
There are many “bellow” instead of “below”. 
In the “Learning Unit Workflow”, why are we referencing the batch3-students-repo? 
Why do students have to push things into their repo if we are not grading the SLUs in the portal? Saving and rerunning the notebook would also not be needed if we aren’t grading notebooks. 
There is also a typo “ds-prep-worksapce” instead of “ds-prep-workspace”.
In the “Older Windows Setup”, we refer a guide and a tutorial. I think we should use the same word in order not to confuse students.
Good job guys!

**Comment by minhhoang1023** [comment]
Some suggestions:
1. Before WSL/Vmware guidelines: Can we leave a note telling people that installing this software should not change how their computer works and is simply an extension of what they already have? It can be scary for people to install it without really understand what is WSL or VMware
2. Git pull sessions: Can we add a session telling students that they need will do a git pull every Monday, and how to do that.
3. Install requirements.txt: Let's add another session show them how to install 
4. Create a Python environment: Do people need to create a different environment for each SLU? Or only one is enough?

**Comment by minhhoang1023** [comment]
@hcastilho @buedaswag Let me know what you think! I can take some parts with you guys as well :)

**Comment by buedaswag** [comment]
hey @minhhoang1023 :D 
1) and 2) fantastic ideas! those make a lot of sense to me, i'll add that.
3) i'll add that
4) short answer: it depends on what packages we will be using in the learning units: are we using lots of exotic packages that have specific dependencies? or are we using vanilla jupyter, numpy and very few packages? if we are only using the basics, there is no need for different virtual environments, however, in the academy this will not be the case, and it would be great IMHO for students to have this covered. 
Long answer: here are 2 big options here (but not the only ones):
A) we create a different VE (virtual environment) for each LU. This would mean that it would be easy ,and would make sense because of its simplicity, to create a virtual environment that would be stored directly on the folder of the project, like so: `python3 -m venv my_env`, and to activate it: `source my_env/bin/activate`
B) we create one VE that we use throughout the prep course. In this case, it makes more sense to store the VE in a location that is easy to remember, the convention is `~/.virtualenvs/`. So to create the VE: `python3 -m venv ~/.virtualenvs/my_env`, and to activate it:`source ~/.virtualenvs/my_env/bin/activate`. Note that this approach also makes a lot of sense for working with multiple VE (just replace `my_env` with the name of your environment) and is actually the conventional way of doing so.

**Comment by minhhoang1023** [comment]
@buedaswag On your question, I think the packages will be quite simple, so things like jupyter, numpy, matplotlib, etc. In the Final project, we'll need to install pygames. For those, do you think having only 1 VE is enough?

**Comment by buedaswag** [comment]
i quickly went through the installation instructions of pygame here:
https://www.pygame.org/wiki/GettingStarted#Pygame%20Installation

and i think we should be fine with a single virtual environment here.

**Comment by minhhoang1023** [comment]
ok that's cool! And since it's an absolute path, students can just activate it the same way every time right?

**Comment by buedaswag** [comment]
yep, that's right, and another neat thing about it is that we can create as many VE as we want an they'll all live in the same place.

i just created a test VE and installed `notebook numpy matplotlib pandas pygame`and they all got installed.

**Comment by minhhoang1023** [comment]
Perfect!

**Comment by buedaswag** [comment]
@rjna :
below: done
batch3-students-repo: done
ds-prep-worksapce: done

I still think it's very usefull for the students to rerun the notebook and make sure there are no mistakes in their code :)

**Pull request merged**
